# Intended file name: omnetpp_cmdenv.ini
# The following .ini file is a modified version of the default parameter file for this scenario, made for headless environments by using the OMNeT++ Cmdenv.
# Cmdenv allows command-line outputs to be redirected to a log file for convenient analysis.
# Rename this file to omnetpp.ini to use it in the scenario, whilst making sure there are no file name conflicts.
# This file was created to allow the envmod config to be run using cmdenv, which required the duplication of the config's body into the General config

[General]

ned-path = .
image-path = ../../images

# network = LuSTNanoScenario
network = artery.veins.World

##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = true
print-undisposed = false

# Disable this to enable "Qtenv", which activates the OMNeT++ GUI. Beware that disabling Cmdenv also disables the output redirect.
user-interface = "Cmdenv"

cmdenv-express-mode = false
cmdenv-autoflush = true
cmdenv-output-file = ".cmdenv-log"
cmdenv-redirect-output = true

cmdenv-status-frequency = 1s
**.cmdenv-log-level = info

sim-time-limit = 1h # Default value: 24h

# **.scalar-recording = true
# **.vector-recording = true

**.debug = false
**.coreDebug = false

*.playgroundSizeX = 1500m
*.playgroundSizeY = 1500m
*.playgroundSizeZ = 50m

# *.playgroundSizeX = 12488m
# *.playgroundSizeY = 12488m
# *.playgroundSizeZ = 50m

##########################################################
# Annotation parameters                                  #
##########################################################
*.annotations.draw = true

##########################################################
# Obstacle parameters
##########################################################
*.obstacles.debug = false
*.obstacles.obstacles = xmldoc("config.xml", "//AnalogueModel[@type='SimpleObstacleShadowing']/obstacles")

##########################################################
#            TraCIScenarioManager parameters             #
##########################################################

*.traci.core.version = -1
*.traci.launcher.typename = "PosixLauncher"
# Uncomment/comment the line below to enable/disable the SUMO GUI (traffic graphics)
*.traci.launcher.sumo = "sumo-gui"
*.traci.launcher.sumocfg = "due.actuated.sumocfg"
*.traci.launcher.port = 9999

*.manager.updateInterval = 1s
*.manager.host = "localhost"
*.manager.port = 9999
*.manager.autoShutdown = false
*.manager.launchConfig = xmldoc("lust.launchd.xml")

##########################################################
#                       RSU SETTINGS                     #
#                                                        #
#                                                        #
##########################################################
*.rsu[0].mobility.x = 1538
*.rsu[0].mobility.y = 945
*.rsu[0].mobility.z = 3

*.rsu[*].applType = "TraCIDemoRSU11p"
*.rsu[*].appl.headerLength = 80 bit
*.rsu[*].appl.sendBeacons = false
*.rsu[*].appl.dataOnSch = false
*.rsu[*].appl.beaconInterval = 1s
*.rsu[*].appl.beaconUserPriority = 7
*.rsu[*].appl.dataUserPriority = 5


##########################################################
#            11p specific parameters                     #
#                                                        #
#                    NIC-Settings                        #
##########################################################
*.connectionManager.sendDirect = true
*.connectionManager.maxInterfDist = 2600m
*.connectionManager.drawMaxIntfDist = false

*.**.nic.mac1609_4.useServiceChannel = false

*.**.nic.mac1609_4.txPower = 20mW
*.**.nic.mac1609_4.bitrate = 6Mbps
*.**.nic.phy80211p.minPowerLevel = -89dBm

*.**.nic.phy80211p.useNoiseFloor = true
*.**.nic.phy80211p.noiseFloor = -98dBm

*.**.nic.phy80211p.decider = xmldoc("config.xml")
*.**.nic.phy80211p.analogueModels = xmldoc("config.xml")
*.**.nic.phy80211p.usePropagationDelay = true

*.**.nic.phy80211p.antenna = xmldoc("antenna.xml", "/root/Antenna[@id='monopole']")
*.node[*].nic.phy80211p.antennaOffsetY = 0 m
*.node[*].nic.phy80211p.antennaOffsetZ = 1.895 m

# Application Layer
*.node[*].applType = "artery.veins.ApplicationLayer"
*.node[*].appl.middleware.updateInterval = 0.1s
*.node[*].appl.middleware.datetime = "2013-06-01 12:35:00"
*.node[*].appl.middleware.services = xmldoc("services.xml")

##########################################################
#                    WaveAppLayer                        #
##########################################################
#*.node[*].applType = "TraCIDemo11p"
#*.node[*].appl.headerLength = 80 bit
#*.node[*].appl.sendBeacons = true
#*.node[*].appl.dataOnSch = false
#*.node[*].appl.beaconInterval = 1s

##########################################################
#                      Mobility                          #
##########################################################
*.node[*].veinsmobilityType.debug = true
*.node[*].veinsmobility.x = 0
*.node[*].veinsmobility.y = 0
*.node[*].veinsmobility.z = 1.895
*.node[*].veinsmobility.setHostSpeed = true
*.node[*].veinsmobility.setHostAcceleration = true
#*.node[*0].veinsmobility.accidentCount = 0
#*.node[*0].veinsmobility.accidentStart = 75s
#*.node[*0].veinsmobility.accidentDuration = 50s

###################
## ENVMOD CONFIG ##
###################


*.node[*].wlan[*].typename = "VanetNic"
*.node[*].wlan[*].radio.channelNumber = 180
*.node[*].wlan[*].radio.carrierFrequency = 5.9 GHz
*.node[*].wlan[*].radio.transmitter.power = 200 mW
*.node[*].wlan[*].radio.radioMediumModule = "radioMediumModule2" # ?

*.node[*].middleware.updateInterval = 0.1s
*.node[*].middleware.datetime = "2018-03-19 10:00:00"
*.node[*].middleware.services = xmldoc("services.xml")

network = artery.envmod.World
**.identityRegistryModule = "idRegistry"
*.traci.mapper.vehicleType = "artery.envmod.Car"

# *.traci.mapper.typename = "traci.MultiTypeModuleMapper"
# *.traci.mapper.vehicleTypes = xml \
# ("\
#     <vehicles> \
#         <vehicle type=\"artery.envmod.Car\" rate=\"0.5\" /> \
#         <vehicle type=\"artery.envmod.PlainVehicle\" rate=\"0.5\" /> \
#     </vehicles> \
# ")

*.environmentModel.drawObstacles = true
*.environmentModel.drawVehicles = true
*.environmentModel.obstacleTypes = "building shop"
*.environmentModel.traciModule = "traci"
*.environmentModel.nodeMobilityModule = ".mobility"

*.node[*].middleware.services = xmldoc("services-envmod.xml")

*.node[*].environmentModel.sensors = xmldoc("sensors.xml")

*.node[*].environmentModel.globalEnvironmentModule = "environmentModel" # ?

*.node[*].environmentModel.*.drawSensorCone = true
*.node[*].environmentModel.*.drawLinesOfSight = true
*.node[*].environmentModel.*.drawDetectedObjects = true
*.node[*].environmentModel.*.drawBlockingObstacles = true

*.node[4].environmentModel.FrontRadar.fovRange = 200.0 m
*.node[4].environmentModel.FrontRadar.fovAngle = 20.0

