# Intended file name: omnetpp_cmdenv.ini
# The following .ini file is a modified version of the default parameter file for this scenario, made for headless environments by using the OMNeT++ Cmdenv.
# Cmdenv allows command-line outputs to be redirected to a log file for convenient analysis.
# Rename this file to omnetpp.ini to use it in the scenario, whilst making sure there are no file name conflicts.

[General]
debug-on-errors = true
print-undisposed = true

# disable this to enable "Qtenv", which activates the OMNeT++ GUI. Beware that disabling Cmdenv also disables the output redirect.
user-interface = "Cmdenv"

cmdenv-express-mode = false 
cmdenv-autoflush = true
# redirect event log output to a file
cmdenv-output-file = ".cmdenv-log"
cmdenv-redirect-output = true

*.traci.core.version = -1
*.traci.launcher.typename = "PosixLauncher"
*.traci.launcher.sumocfg = "highway.sumocfg"

# Uncomment/comment the line below to enable/disable the SUMO GUI (traffic graphics).
# Cmdenv still allows the SUMO GUI to be displayed
*.traci.launcher.sumo = "sumo-gui"

# separate random number generator for vehicle penetration rate
num-rngs = 2
*.traci.mapper.rng-0 = 1

# Cmdenv does not ask for the config, so it assumes General, thus not using the inet config as defined in this .ini.
# This is why the inet config is being duplicated into General. 
# To use this emulated config, ensure that any other emulated config, i.e. 
# blocks of parameters that had to be duplicated from .ini config sections to the General config section, are commented out.

#################
## INET CONFIG ##
#################

# network = artery.inet.World 

# *.node[*].wlan[*].typename = "VanetNic"
# *.node[*].wlan[*].radio.channelNumber = 180
# *.node[*].wlan[*].radio.carrierFrequency = 5.9 GHz
# *.node[*].wlan[*].radio.transmitter.power = 200 mW

# *.node[*].middleware.updateInterval = 0.1s
# *.node[*].middleware.datetime = "2018-03-19 10:00:00"
# *.node[*].middleware.services = xmldoc("services.xml")

#####################
## END INET CONFIG ##
#####################

# The section below duplicates elements from the inet config because it cannot automatically extend the inet config using the "extends" parameter
# When using this section, please comment the emulated INET config section before this one

###################
## ENVMOD CONFIG ##
###################

network = artery.envmod.World
**.identityRegistryModule = "idRegistry"
*.traci.mapper.vehicleType = "artery.envmod.Car"

# *.traci.mapper.typename = "traci.MultiTypeModuleMapper"
# *.traci.mapper.vehicleTypes = xml \
# ("\
#     <vehicles> \
#         <vehicle type=\"artery.envmod.Car\" rate=\"0.5\" /> \
#         <vehicle type=\"artery.envmod.PlainVehicle\" rate=\"0.5\" /> \
#     </vehicles> \
# ")

*.environmentModel.drawObstacles = true
*.environmentModel.drawVehicles = true
*.environmentModel.obstacleTypes = "building shop"
*.environmentModel.traciModule = "traci"
*.environmentModel.nodeMobilityModule = ".mobility"

*.node[*].wlan[*].typename = "VanetNic"
*.node[*].wlan[*].radio.channelNumber = 180
*.node[*].wlan[*].radio.carrierFrequency = 5.9 GHz
*.node[*].wlan[*].radio.transmitter.power = 200 mW

*.node[*].middleware.updateInterval = 0.1s
*.node[*].middleware.datetime = "2018-03-19 10:00:00"
*.node[*].middleware.services = xmldoc("services-envmod.xml")

*.node[*].environmentModel.sensors = xmldoc("sensors.xml")

*.node[*].environmentModel.*.drawSensorCone = true
*.node[*].environmentModel.*.drawLinesOfSight = true
*.node[*].environmentModel.*.drawDetectedObjects = true
*.node[*].environmentModel.*.drawBlockingObstacles = true

*.node[4].environmentModel.FrontRadar.fovRange = 200.0 m
*.node[4].environmentModel.FrontRadar.fovAngle = 20.0

#######################
## END ENVMOD CONFIG ##
#######################

[Config inet]

network = artery.inet.World 

*.node[*].wlan[*].typename = "VanetNic"
*.node[*].wlan[*].radio.channelNumber = 180
*.node[*].wlan[*].radio.carrierFrequency = 5.9 GHz
*.node[*].wlan[*].radio.transmitter.power = 200 mW

*.node[*].middleware.updateInterval = 0.1s
*.node[*].middleware.datetime = "2018-03-19 10:00:00"
*.node[*].middleware.services = xmldoc("services.xml")

[Config inet_mco]
extends = inet
*.node[*].numRadios = 2
*.node[*].wlan[1].radio.channelNumber = 176
*.node[*].middleware.services = xmldoc("services-mco.xml")
*.node[*].middleware.mcoPolicy = xml("<mco default=\"CCH\"><application id=\"16480\" channel=\"176\" /></mco>")

[Config envmod]
extends = inet
network = artery.envmod.World
**.identityRegistryModule = "idRegistry"
*.traci.mapper.vehicleType = "artery.envmod.Car"

# *.traci.mapper.typename = "traci.MultiTypeModuleMapper"
# *.traci.mapper.vehicleTypes = xml \
# ("\
#     <vehicles> \
#         <vehicle type=\"artery.envmod.Car\" rate=\"0.5\" /> \
#         <vehicle type=\"artery.envmod.PlainVehicle\" rate=\"0.5\" /> \
#     </vehicles> \
# ")

*.environmentModel.drawObstacles = true
*.environmentModel.drawVehicles = true
*.environmentModel.obstacleTypes = "building shop"
*.environmentModel.traciModule = "traci"
*.environmentModel.nodeMobilityModule = ".mobility"

*.node[*].middleware.services = xmldoc("services-envmod.xml")

*.node[*].environmentModel.sensors = xmldoc("sensors.xml")

*.node[*].environmentModel.*.drawSensorCone = true
*.node[*].environmentModel.*.drawLinesOfSight = true
*.node[*].environmentModel.*.drawDetectedObjects = true
*.node[*].environmentModel.*.drawBlockingObstacles = true

*.node[4].environmentModel.FrontRadar.fovRange = 200.0 m
*.node[4].environmentModel.FrontRadar.fovAngle = 20.0