[General]
network = artery.inet.World
sim-time-limit = 5s
user-interface = "Cmdenv"
cmdenv-express-mode = false
**.cmdenv-log-level = info
cmdenv-output-file = ".cmdenv-log"
cmdenv-redirect-output = true

*.traci.core.version = -1
*.traci.launcher.typename = "PosixLauncher"
*.traci.launcher.sumocfg = "highway.sumocfg"

*.node[*].middleware.datetime = "2013-06-01 12:00:00"
*.node[*].middleware.updateInterval = 0.1s
*.node[*].middleware.services = xmldoc("services.xml")
*.node[*].middleware.CA.fixedRate = true
*.node[*].middleware.CA.minInterval = 1s
*.node[*].middleware.CA.maxInterval = 1s
*.node[*].middleware.CA.withDccRestriction = false

# Attacker Config (ConstPos)
*.node[1].middleware.CA.isAttacker = true
*.node[1].middleware.CA.misbehaviorType = 1
*.node[1].middleware.CA.startAttack = 0.0
*.node[1].middleware.CA.falsificationOffset = 100m
*.node[1].middleware.CA.attackProbability = 1.0
